# General Settings
title: "Axal SA"
email: "tortoizthemes@gmail.com"
email_2: "support@tortoizthemes.com"
description: >- # this means to ignore newlines until "baseurl:"
  Axal SA is a venture capital firm supporting tech startups with sustainable solutions, providing funding, resources, and global partnerships to drive innovation and growth.

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: 'Rue Robert-Céard 6 <br>1204 Geneva<br /> Switzerland'
phone_number:
copyright_text: "© 2024 Axal SA. All rights reserved."

google_analytics:
  enable: true
  key: "G-9DFN7CMC8S"  # UA-664136761-1

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "https://x.com/AxalGlobal"
      icon: "jam jam-twitter"

    - url: "https://www.instagram.com/axalglobal"
      icon: "jam jam-instagram"

    - url: "https://www.facebook.com/AxalGlobal"
      icon: "jam jam-facebook"

    - url: "https://www.linkedin.com/company/axalglobal"
      icon: "jam jam-linkedin"


external_links:
  title: "Learn More"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Insig"
    - url: "#"
      text: "Projects"
    - url: "#"
      text: "Pricing"
    - url: "#"
      text: "Features"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "/team"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

footer_newsletter:
  title: "Our Newsletter"
  sub_title: "Subscribe to our newsletter to get our news & deals delivered to your inbox!"
  subscribe_button_text: "Join"


one_page_nav_settings:
  links:
    - text: "Our Team"
      url: "/team"
    - text: "Philosophy"
      url: "#services"
    - text: "Our Product"
      url: "#process"
    - text: "Companies"
      url: "#experiences"
    - text: "Insights"
      url: "#portfolio"
    - text: "Ops"
      url: "https://axal.io"
    - text: "Connect"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"